local FlowProperties = {
	LEFT = "Left",
	RIGHT = "Right",
	TOP = "Top",
	BOTTOM = "Bottom",
	PADDING_LEFT = "PL",
	PADDING_TOP = "PT",
	PADDING_RIGHT = "PR",
	PADDING_BOTTOM = "PB",
	MARGIN_LEFT = "ML",
	MARGIN_TOP = "MT",
	MARGIN_RIGHT = "MR",
	MARGIN_BOTTOM = "MB",
	BORDER_LEFT = "BL",
	BORDER_TOP = "BT",
	BORDER_RIGHT = "BR",
	BORDER_BOTTOM = "BB",
	WIDTH = "Width",
	HEIGHT = "Height",
	MIN_WIDTH = "MinWidth",
	MIN_HEIGHT = "MinHeight",
	MAX_WIDTH = "MaxWidth",
	MAX_HEIGHT = "MaxHeight",
	DIRECTION = "Direction",
	FLEX_GROW = "FlexGrow",
	FLEX_SHRINK = "FlexShrink",
	FLEX_BASIS = "FlexBasis",
	POSITION_TYPE = "PositionType",
	FLEX_DIRECTION = "FlexDirection",
	FLEX_WRAP = "FlexWrap",
	JUSTIFY_CONTENT = "JustifyContent",
	ALIGN_ITEMS = "AlignItems",
	ALIGN_SELF = "AlignSelf",
	ALIGN_CONTENT = "AlignContent",
	DISPLAY = "Display",
}

return table.freeze(FlowProperties)
